INSERT INTO question(content, answer) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", 0),
("Donec porttitor turpis pretium semper semper.", 1),
("Phasellus venenatis magna sed orci pharetra ultricies.", 1),
("Duis eu risus ut eros pulvinar ornare bibendum non eros.", 1),
("Vestibulum ut erat quis lacus malesuada malesuada quis nec tellus.", 1),
("Etiam aliquet metus sit amet urna finibus, sit amet auctor lacus maximus.", 0),
("Aenean pellentesque quam ac tellus commodo tempor.", 0),
("Integer at eros vitae orci lobortis iaculis vel a tortor.", 1),
("Quisque non justo id ex feugiat tincidunt.", 0),
("Vestibulum aliquet nibh vitae justo pulvinar rutrum.", 0),
("Maecenas vulputate leo at arcu posuere cursus.", 1),
("Phasellus ut neque cursus leo tristique consectetur eu ac ipsum.", 0),
("Morbi eget dui lobortis urna consequat posuere.", 0),
("Integer eu quam ac eros maximus dignissim et a augue.", 0),
("Integer maximus enim tincidunt est sollicitudin, sollicitudin gravida ligula sodales.", 0),
("Etiam tristique magna nec bibendum finibus.", 1),
("Suspendisse gravida nunc quis commodo dignissim.", 1),
("Quisque a ligula sed orci sodales blandit.", 0),
("Quisque imperdiet urna in risus molestie, eget consequat augue semper.", 1),
("Integer aliquet nibh in lorem ullamcorper fringilla.", 1),
("In vitae libero bibendum, imperdiet augue et, condimentum mauris.", 1),
("Proin pellentesque enim eget mi tempor mattis.", 0),
("Mauris malesuada elit eget nulla euismod convallis.", 0),
("Quisque a quam eu massa pellentesque ornare.", 1),
("Fusce congue diam et quam hendrerit efficitur.", 1),
("Aenean eget sapien non metus dictum ultricies vitae nec ligula.", 1),
("Proin bibendum elit eu sagittis aliquet.", 0),
("Fusce mattis justo at lorem dignissim rutrum.", 1),
("Proin rutrum metus ac fermentum luctus.", 1),
("Suspendisse tempor leo quis velit malesuada sagittis.", 1),
("Nam laoreet justo sed ultricies sagittis.", 1),
("In mollis ipsum non cursus semper.", 1),
("Ut quis tortor ultricies, dapibus sapien convallis, gravida risus.", 1),
("Nam et urna eu libero consectetur volutpat nec ac quam.", 0),
("Nullam aliquet nisi a arcu cursus ullamcorper.", 1),
("In rutrum mauris molestie lacus condimentum lobortis.", 1),
("Sed non felis mattis, luctus nunc ac, pretium quam.", 1),
("Nam at neque ornare, porttitor nulla in, ornare nulla.", 0),
("Aenean suscipit urna ut orci aliquam porttitor.", 0),
("Nullam sed mauris et turpis gravida scelerisque.", 1)